{
 "title": "dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 24h transfer in",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select to_address ,count(from_address) from \"TransferHeros\"  where  create_time  BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\nand   buy_on_mp  is null and from_address <> '0x0000000000000000000000000000000000000000'\nand to_address <> '0x0000000000000000000000000000000000000000' \ngroup by to_address order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 24h transfer out",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select from_address ,count(from_address) from \"TransferHeros\"  where  create_time  BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\nand   buy_on_mp  is null and from_address <> '0x0000000000000000000000000000000000000000'\nand to_address <> '0x0000000000000000000000000000000000000000' \ngroup by from_address order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 24h buy low price(<10he)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select buyer,count(buyer) from \"MatchTransactions\" mt where  create_time  BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\nand price < 10 group by buyer  order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 24h sell low price(<10he)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select seller ,count(seller) from \"MatchTransactions\" mt where  create_time  BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\nand price < 10 group by seller  order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 12h sell",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select seller ,count(seller) from \"MatchTransactions\" mt where  create_time  BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\ngroup by seller  order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 12h mint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "\nselect to_address ,count(from_address) from \"TransferHeros\"  where  create_time  BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\nand   buy_on_mp  is null and from_address = '0x0000000000000000000000000000000000000000'\ngroup by to_address order by count desc limit 100"
    }
   ]
  },
  {
   "title": "Top 12h withdraw",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select to_address,sum(amount) as vol  from \"HotWalletTransfers\" where  \"type\" ='HOTWALLET' and from_address = '0xAe197c8C8cdebbA25dB099ed41906A668B1835aA'\nand  create_time  BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\ngroup  by to_address order by vol desc  limit 100"
    }
   ]
  }
 ]
}