{
 "title": "mainnet dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hePrice",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Ingame", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingame",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "cacheDurationSeconds": 1800,
     "fields": [
      { "jsonPath": "$.total_user", "name": "Total user" }
     ],
     "method": "GET",
     "urlPath": "/playfab/count_total_user"
    },
    {
     "cacheDurationSeconds": 1800,
     "fields": [
      { "jsonPath": "$.he_ingame", "name": "HE ingame" }
     ],
     "method": "GET",
     "urlPath": "/playfab/get_he_ingame"
    },
    {
     "cacheDurationSeconds": 1800,
     "fields": [
      { "jsonPath": "$.daily_active_user", "name": "Daily active user" }
     ],
     "method": "GET",
     "urlPath": "/playfab/count_daily_active_user"
    }
   ]
  },
  { "title": "Spend fee", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Spend",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  type,\n  count(1) AS \"transactions\",\n  sum(amount) as \"total amount (HE)\",\n   sum(tx_fee) AS \"fee (BNB)\"\nFROM \"HotWalletTransfers\" where type is not null\ngroup by type"
    },
    {
     "rawSql": "select 'ISSUED HERO' as type,count(1) AS \"transactions\",sum(a.tx_fee) as \"fee (BNB)\" \nfrom (select max(tx_fee) as tx_fee \nfrom \"TransferHeros\" \nwhere from_address = '0x0000000000000000000000000000000000000000' group by tx_hash) a"
    }
   ]
  },
  {
   "title": "Spend fee ${__from:date:DD-MM-YYYY} - ${__to:date:DD-MM-YYYY}",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  type,\n  count(1) AS \"transactions\",\n  sum(amount) as \"total amount (HE)\",\n   sum(tx_fee) AS \"fee (BNB)\"\nFROM \"HotWalletTransfers\" where  $__timeFilter(create_time) and type is not null\ngroup by type"
    },
    {
     "rawSql": "select 'ISSUED HERO' as type,count(1) AS \"transactions\",sum(a.tx_fee) as \"fee (BNB)\" \nfrom (select max(tx_fee) as tx_fee \nfrom \"TransferHeros\" \nwhere from_address = '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time) group by tx_hash) a"
    }
   ]
  },
  {
   "title": "Total User spend/earn HE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('hour', a.\"create_time\") as time,\n    sum(\"amount\")  as \"amount\"\n  from (select create_time,\"amount\" from \"HotWalletTransfers\" \n  where \"type\"  in ('SUMMON','LIMIT_BREAK','SPEND_FEE','BUY_SLOT','DEPOSIT','CLAN_MAP','EDIT_NAME','PURCHASE_ITEM_DUNGEON','REQUEST_HERO','UNION_BLESSING')) a\n  group by 1\n)\nselect\n  time,\n  sum(\"amount\") over (order by time asc rows between unbounded preceding and current row) as \"spend onchain\" \nfrom data order by time;"
    },
    {
     "rawSql": "select value::float as \"he_ingame\", date_trunc('hour', \"createdAt\") as time from \"Snapshots\" where key = 'PLAYFAB_HE_INGAME'   and $__timeFilter(\"createdAt\")"
    },
    {
     "rawSql": "select value::float as \"claimed\", date_trunc('hour', \"createdAt\") as time from \"Snapshots\" where key = 'HOTWALLET'   and $__timeFilter(\"createdAt\")"
    }
   ]
  },
  {
   "title": "Hot wallet balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 30,
     "fields": [
      { "jsonPath": "$.balanceHE", "name": "HE", "type": "number" },
      { "jsonPath": "$.balanceBNB", "language": "jsonpath", "name": "BNB", "type": "number" },
      { "jsonPath": "$.timestamp", "language": "jsonpath", "name": "time", "type": "time" }
     ],
     "method": "GET",
     "urlPath": "/api/hot-wallet-balance"
    }
   ]
  },
  {
   "title": "Admin wallet",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "body": "[\n\"0xd998eA274C1EdCCE9ee97182a112735441f21dbE\",\n\"0xA6becC51407912435449D0be2CeB3C9196a2ee77\",\n\"0x314999539150f8283Da6b73fb50E44E8E1B0B0b1\",\n\"0xb1c7995EEb18291eE8549FDe5Fce5ff88A60AF36\",\n\"0xF0C55B7C5F508EdF926CE9bd06e2330053a5444C\",\n\"0xE242d2c6Bf8Ed7268BD4E231c260458B8F0bf560\",\n\"0x335F1AC72d65F1189D5873c3DDBa717FB14db610\",\n\"0xc19BEAfc3d36F90eFef74d8500EF0135781b2E4b\",\n\"0xc1B3F809a01C4c9117B0810105ceB320d713eA4f\",\n\"0x3Ca2e5A84496741b652599aCBe62347c5EDb1418\",\n\"0x67Fd0bA81980B173e9F0Be8b9EE9dEEac38562d5\",\n\"0x29B530f4b5A7a2707617267A98808fef39311925\",\n\"0x3E0A28B8d36Aee33F9F96Ec361964F47Ce5347EB\",\n\"0x2EAC7Afd31c75FfD49D7a8f000BE0EA65CE49ae6\",\n\"0xb1F2CD38bFaE1422e81C30f756c21A03752cA881\",\n\"0xe5ae9531d7E22CD38Af94AbfcC8be8c890bE828a\",\n\"0x45A7f7a346b081B5dD36e6d42Af920212466Bb4c\",\n\"0x05ff201195391251e3BfE9fD86811e7691e4Bdb7\",\n\"0xD0b69fE897A9FbEe27628a0843eC10F067965471\",\n\"0x34B63f8b3751CAFaD8d72C2e25BAA2ebFC104c2a\",\n\"0x0818Fa793aC24681588174c9a6e4cf6c91B5AE2a\",\n\"0x4641D906B7F921Cc9AEca73607429EC01146406A\",\n\"0xc1fFC31E9c8079038D6985489ee2def37E996B93\",\n\"0x73827e3aE5dce0A08cf9D655438399569A0aA184\",\n\"0xfdac6612CB9CCFbc11E0Ae134530569327F75FC3\",\n\"0xA9ce51A5b71e788e52d96cbB6Ba4eD041643B2C5\",\n\"0x15e6ed1a61B3629453A2529941B6889cB3e9f8CD\",\n\"0x8Dfd57A80639b815Ad03612a16c2C3D75E78Ab85\",\n\"0xf8096a55483720CCB1295B7c6218e8A29ce75dD5\",\n\"0x7d4e63757B935C010bCfE025f24413db246B87BF\",\n\"0x39e616B40e14e014E00e52e2c7E81826512DDD78\",\n\"0x2759166b005c3a97B46358c1a6B031ACD7aA2c46\",\n\"0x92E233D1cdBf9D65668e9dc29BF5D6f79D18f663\",\n\"0x5a7ac87Cd9E2548DCe34231743Cd6d10aB944FA6\",\n\"0x54A03293b9AA24248804e482D2C693c17b9A3Be0\",\n\"0x7d51fbF253b43aDDB3CbAa9aB52c0c9247DB7066\",\n\"0x3B623e0bb6f416023B2DD696bB882f2AbD429a2B\",\n\"0xCa2A5823e58DFB3EBb495AaD7533bfa79B32D39B\",\n\"0x7C24115FC69a5750b630e136e14e5b2dAF911000\",\n\"0x54F1b0F8f6aE39e667aaFE28827A9Ff3C139FEf0\",\n\"0xC892c6E7d2Fdc16aC79A1f554EAA38b749B10c0D\"\n]",
     "fields": [
      { "jsonPath": "$[*].address ", "language": "jsonata", "name": "Address", "type": "string" },
      { "jsonPath": "$[*].balanceBNB ", "language": "jsonata", "name": "BNB", "type": "number" },
      { "jsonPath": "$[*].balanceHE", "language": "jsonata", "name": "HE", "type": "number" }
     ],
     "method": "POST",
     "urlPath": "/balanceOfListWallet"
    }
   ]
  },
  { "title": "Total user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total user ",
   "type": "stat",
   "description": "onchain data",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "SELECT\n  max(create_time) AS \"time\",\n  count(DISTINCT to_address) as total \nFROM \"TransferHeros\"\nwhere to_address != '0x0000000000000000000000000000000000000000'\n"
    }
   ]
  },
  {
   "title": "Total user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('hour', a.create_time) as day,\n    count(a.to_address) as total\n  from (select to_address,min(create_time) as create_time from \"TransferHeros\" where to_address != '0x0000000000000000000000000000000000000000' group by to_address) a\n  group by 1 \n)\n\nselect\n  day as time,\n  sum(total) over (order by day asc rows between unbounded preceding and current row)\nfrom data"
    }
   ]
  },
  {
   "title": "Daily user increasement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\nselect count(b.to_address) as users,b.time as time from (select min(a.time) as time, a.to_address from (SELECT\n  date_trunc('day',create_time) AS \"time\",\n to_address \nFROM \"TransferHeros\"\nwhere to_address != '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time)\n) a group by a.to_address) b group by b.time order by time"
    }
   ]
  },
  {
   "title": "Holder nft hero",
   "type": "stat",
   "description": "onchain data",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct owner) as holder from \"HeroV2s\" hvs where not is_burned "
    }
   ]
  },
  { "title": "Total hero", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top 50 holder",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "select owner as address, count(1) as hold from \"HeroV2s\" hvs where not is_burned group by \"owner\" order by hold desc limit 50"
    }
   ]
  },
  {
   "title": "Top 50 hero by tier",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "select  owner,\ntier,\ntoken_id,\nname,\ncase \nwhen tier = 'Common' then 1\nwhen tier = 'Rare' then 2\nwhen tier = 'Rare+' then 3\nwhen tier = 'Epic' then 4\nwhen tier = 'Epic+' then 5\nwhen tier = 'Legendary' then 6\nwhen tier = 'Legendary+' then 7\nwhen tier = 'Immortal' then 8\nwhen tier = 'Immortal+' then 9\nwhen tier = 'Ultimate' then 10\nwhen tier = 'Ultimate 1' then 11\nwhen tier = 'Ultimate 2' then 12\nwhen tier = 'Ultimate 3' then 13\nwhen tier = 'Ultimate 4' then 14\nwhen tier = 'Ultimate 5' then 15\n\n\nelse 20\nend as tier_weight\nfrom \"HeroV2s\" hvs where tier <> '' and owner <> '0x0000000000000000000000000000000000000000'\n\norder by  tier_weight desc   limit 50"
    }
   ]
  },
  {
   "title": "Total heroes issue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day',NOW()) AS \"time\",\n  count(to_address) as \"Issued Heroes\" \nFROM \"TransferHeros\"\nwhere from_address = '0x0000000000000000000000000000000000000000' "
    },
    {
     "rawSql": "SELECT\n  date_trunc('day',NOW()) AS \"time\",\n  count(to_address) as \"Burned Heroes\" \nFROM \"TransferHeros\"\nwhere to_address = '0x0000000000000000000000000000000000000000' "
    }
   ]
  },
  {
   "title": "heroes",
   "type": "table",
   "description": "onchain data",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 49 },
   "targets": [
    {
     "rawSql": "select  name,tier, count(1) as heroes  from \"HeroV2s\" where name <> '' group by name,tier\norder by name,tier"
    }
   ]
  },
  {
   "title": "Heroes",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 49 },
   "targets": [
    {
     "rawSql": "select  name, count(1) as heroes  from \"HeroV2s\" where name <> ''  group by name\n order by \"heroes\" desc"
    }
   ]
  },
  {
   "title": "Heroes issue ${__from:date:DD-MM-YYYY} - ${__to:date:DD-MM-YYYY}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(to_address) as \"Issued Heroes\" \nFROM \"TransferHeros\"\nwhere from_address = '0x0000000000000000000000000000000000000000'  and $__timeFilter(create_time)"
    },
    {
     "rawSql": "SELECT\n\n  count(to_address) as \"Burned Heroes\" \nFROM \"TransferHeros\"\nwhere to_address = '0x0000000000000000000000000000000000000000'  and $__timeFilter(create_time)"
    }
   ]
  },
  {
   "title": "Distinct heroes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"Distinct heroes\" from (select  name  from \"HeroV2s\" where not is_burned and name <> '' group by name\norder by name) a"
    }
   ]
  },
  {
   "title": "class",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select class, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' group by class\n  order by heroes"
    }
   ]
  },
  {
   "title": "race",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select race, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' group by race\n  order by heroes"
    }
   ]
  },
  {
   "title": "tier",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select tier, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' group by tier\n  order by heroes"
    }
   ]
  },
  {
   "title": "Issued Heroes type",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "\n select type , count(1) as heroes from \"HeroV2s\"   group by type\n  order by heroes\n"
    }
   ]
  },
  {
   "title": "Summon Heroes type",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n select type_issued , count(1) as heroes from \"HeroV2s\" where  \"type\" = 'SUMMON'  group by type_issued\n  order by heroes\n"
    }
   ]
  },
  {
   "title": "Heroes summon - tier basic",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n select tier_basic , count(1) as heroes from \"HeroV2s\" where  \"type\" = 'SUMMON' and name <> ''  group by tier_basic\n  order by heroes\n"
    }
   ]
  },
  {
   "title": "Heroes scroll summon - tier basic",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n select tier_basic , count(1) as heroes from \"HeroV2s\" where  \"type\" = 'SUMMON' and name <> '' and type_issued='Scroll'  group by tier_basic\n  order by heroes\n"
    }
   ]
  },
  {
   "title": "Daily summon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "select b.type_issued,a.time,count(1) as heroes  from \n(select token_id,date_trunc('day',create_time) AS \"time\" from \"TransferHeros\" \nwhere from_address = '0x0000000000000000000000000000000000000000' and\n  $__timeFilter(create_time::date) ) a,\n\"HeroV2s\" b where a.token_id = b.token_id and b.\"type\" = 'SUMMON' group by a.time ,b.type_issued\n"
    }
   ]
  },
  {
   "title": "Daily hero",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "SELECT\n  date_trunc('day',create_time) AS \"time\",\n  count(to_address) as \"issue hero\" \nFROM \"TransferHeros\"\nwhere from_address = '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time)\ngroup by time  order by time"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "SELECT\n  date_trunc('day',create_time) AS \"time\",\n  count(to_address) as \"burned hero\" \nFROM \"TransferHeros\"\nwhere to_address = '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time)\ngroup by time  order by time"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "rawSql": "select a.time,b.tier_basic,count(1) as \"heroes rare issued\" from (select token_id,date_trunc('day',create_time) AS \"time\"\nFROM \"TransferHeros\"\nwhere from_address = '0x0000000000000000000000000000000000000000'\nand $__timeFilter(create_time)) a, \"HeroV2s\" b where a.token_id = b.token_id and b.tier_basic = 'Rare' \ngroup by a.time,b.tier_basic\n "
    }
   ]
  },
  {
   "title": "Total heroes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', create_time) as day,\n   count(DISTINCT token_id) as total \n  from \"TransferHeros\" \n  where   from_address  = '0x0000000000000000000000000000000000000000'\n  group by 1\n)\n\nselect\n  day as time,\n  sum(total) over (order by day asc rows between unbounded preceding and current row)  as \"Total issued\"\nfrom data"
    },
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', create_time) as day,\n   count(DISTINCT token_id) as total \n  from \"TransferHeros\" \n  where   to_address  = '0x0000000000000000000000000000000000000000'\n  group by 1\n)\n\nselect\n  day as time,\n  sum(total)  over (order by day asc rows between unbounded preceding and current row) as \"Total burned\"\nfrom data\n"
    }
   ]
  },
  {
   "title": "Daily % burned/issued ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', create_time) as day,\n   count(DISTINCT token_id) as total \n  from \"TransferHeros\" \n  where   from_address  = '0x0000000000000000000000000000000000000000'\n  group by 1\n)\n\nselect\n  day as time,\n  sum(total)  over (order by day asc rows between unbounded preceding and current row) as \"Total issued\"\nfrom data\n\n"
    },
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', create_time) as day,\n   count(DISTINCT token_id) as total \n  from \"TransferHeros\" \n  where   to_address  = '0x0000000000000000000000000000000000000000'\n  group by 1\n)\n\nselect\n  day as time,\n  sum(total)  over (order by day asc rows between unbounded preceding and current row) as \"Total burned\"\nfrom data\n\n"
    }
   ]
  },
  { "title": "Market place", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Marketplace ",
   "type": "stat",
   "description": "Data sell heroes on marketplace",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(*) as \"Matching tx\",sum(price) as \"Matching volume in HE\" ,sum(price) * $hePrice as \"Matching volume in USD\", sum(market_fee) as \"Revenue in HE\", sum(market_fee)* $hePrice as \"Revenue in USD\"   from \"MatchTransactions\"\n"
    }
   ]
  },
  {
   "title": "Marketplace ${__from:date:DD-MM-YYYY} - ${__to:date:DD-MM-YYYY}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(*) as \"Matching tx\",sum(price) as \"Matching volume in HE\" ,sum(price) * $hePrice as \"Matching volume in USD\", sum(market_fee) as \"Revenue in HE\", sum(market_fee)* $hePrice as \"Revenue in USD\"   from \"MatchTransactions\" where $__timeFilter(create_time)\n"
    }
   ]
  },
  {
   "title": "Sell package nft",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select t.count as \"Issued\", b.count as \"Burned\"  from \n(select  count(1) from \"PackageNFTs\" where to_address = '0x0000000000000000000000000000000000000000') b,\n(select  count(1)  from \"PackageNFTs\" where  from_address  = '0x0000000000000000000000000000000000000000') t"
    },
    {
     "rawSql": "select sum(a.price) as \"Revenue\"  from (select max(price) as price from \"PackageNFTs\" group by tx_hash) a"
    }
   ]
  },
  {
   "title": "Sell package nft ${__from:date:DD-MM-YYYY} - ${__to:date:DD-MM-YYYY}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select t.count as \"Issued\", b.count as \"Burned\"  from \n(select  count(1) from \"PackageNFTs\" where to_address = '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time)) b,\n(select  count(1)  from \"PackageNFTs\" where  from_address  = '0x0000000000000000000000000000000000000000' and $__timeFilter(create_time)) t"
    },
    {
     "rawSql": "select sum(price) as \"Revenue\"  from \"PackageNFTs\" where $__timeFilter(create_time)"
    }
   ]
  },
  {
   "title": "Marketplace data",
   "type": "stat",
   "description": "Marketplace api",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 30,
     "fields": [
      { "jsonPath": "$.totalItems", "name": "Total item" },
      { "jsonPath": "$.totalSaleItems", "language": "jsonpath", "name": "Listing item" },
      { "jsonPath": "$.totalUsers", "language": "jsonpath", "name": "Total user" },
      { "jsonPath": "$.totalVolume", "language": "jsonpath", "name": "Total volume(HE)" }
     ],
     "method": "GET",
     "urlPath": "/market-data/statistic"
    }
   ]
  },
  {
   "title": "Marketplace listing items",
   "type": "graph",
   "description": "Data snapshot from marketplace api",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  CAST(value AS DECIMAL ) AS \"items\"\nFROM \"Snapshots\"\nWHERE\n  $__timeFilter(\"createdAt\") AND\n  key = 'MARKETPLACE_LISTING_ITEMS'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Marketplace total user",
   "type": "graph",
   "description": "Data snapshot from marketplace api",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  CAST(value AS DECIMAL ) AS \"users\"\nFROM \"Snapshots\"\nWHERE\n  $__timeFilter(\"createdAt\") AND\n  key = 'MARKETPLACE_TOTAL_USER'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Marketplace listing vol",
   "type": "graph",
   "description": "Data snapshot from marketplace api",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  CAST(value AS DECIMAL ) AS \"volume\"\nFROM \"Snapshots\"\nWHERE\n  $__timeFilter(\"createdAt\") AND\n  key = 'MARKETPLACE_LISTING_VOLUME'\nORDER BY 1"
    }
   ]
  },
  { "title": "HE token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "HE token",
   "type": "stat",
   "description": "Coingecko data",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.heroes-empires.usd", "name": "Price" },
      {
       "jsonPath": "$.heroes-empires.usd_24h_change",
       "language": "jsonpath",
       "name": "24h change"
      },
      { "jsonPath": "$.heroes-empires.usd_24h_vol", "language": "jsonpath", "name": "24h vol" },
      {
       "jsonPath": "$.heroes-empires.usd_market_cap",
       "language": "jsonpath",
       "name": "usd marketcap"
      }
     ],
     "method": "GET",
     "urlPath": "/simple/price?ids=heroes-empires&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true"
    }
   ]
  },
  {
   "title": "HE price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.prices[*].0", "name": "Time", "type": "time" },
      { "jsonPath": "$.prices[*].1", "language": "jsonpath", "name": "price" }
     ],
     "method": "GET",
     "urlPath": "/coins/heroes-empires/market_chart?vs_currency=usd&days=90&interval=hour"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {
     "rawSql": "SELECT \"value\"\nFROM \"Snapshots\" where key = 'SYSTEM_CONFIG_KEY'"
    }
   ]
  }
 ]
}