{
 "title": "user dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "address", "label": "wallet address" }
  ]
 },
 "panels": [
  {
   "title": "Address",
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": { "content": "Address: ${address}" },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.he_balance", "name": "HE", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/playfab/get_user_he_ingame/${address}"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.balanceHE", "name": "HE", "type": "number" },
      { "jsonPath": "$.balanceBNB", "language": "jsonpath", "name": "BNB", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "address",
       "${address}"
      ]
     ],
     "urlPath": "/balanceOf"
    },
    {
     "rawSql": " select  count(1) as \"number of hero\" from \"HeroV2s\" where not is_burned and name <> '' and owner='$address'\n  "
    }
   ]
  },
  { "title": "User data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "address" },
  {
   "title": "HE spend",
   "type": "table",
   "description": "HE token user spend ingame for summon hero and limit break",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n type,\n  sum(amount) AS \"amount\"\n \nFROM \"HotWalletTransfers\"\nWHERE\n  $__timeFilter(\"create_time\") AND\n  from_address = '$address' or to_address = '$address' and type is not null\nGROUP BY type\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Daily spend HE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n type,\n sum(amount) as amount ,\n date_trunc('day',create_time) as time\nFROM \"HotWalletTransfers\"\nWHERE\n  $__timeFilter(create_time) and from_address='$address' and type is not null\n   group by \"type\",time  order by time;\n"
    }
   ]
  },
  {
   "title": "Spend token history",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n type,\n amount ,\ntx_hash,\n create_time as time\nFROM \"HotWalletTransfers\"\nWHERE\n  $__timeFilter(\"create_time\") AND\n  from_address = '$address' and type is not null\norder by create_time desc"
    }
   ]
  },
  {
   "title": "Daily claim ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n type,\n sum(amount) as HE ,\n date_trunc('day',create_time) as time\nFROM \"HotWalletTransfers\"\nWHERE\n  $__timeFilter(create_time) and to_address='$address' and type is not null\n   group by \"type\",time  order by time;\n"
    }
   ]
  },
  {
   "title": "Hero transfer histories",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n \n  token_id,\n   create_time AS \"time\",\n   tx_hash,\n  from_address,\n   to_address,\n  case when from_address = '0x0000000000000000000000000000000000000000' then 'mint'\n  when to_address = '0x0000000000000000000000000000000000000000' then 'burn'\n  when buy_on_mp = true and to_address = '$address' then 'by on market'\n  when buy_on_mp = true and from_address = '$address' then 'sell on market'\n  when from_address = '$address' then 'transfer out'\n  when to_address = '$address' then 'transfer in'\n  else 'transfer'\n  end as \"type\"\nFROM \"TransferHeros\"\nWHERE\n  $__timeFilter(create_time) AND\n( from_address = '$address' OR\n  to_address = '$address')\nORDER BY create_time desc"
    }
   ]
  },
  {
   "title": "Heroes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT token_id, name,race,class,tier,tier_basic,type\nFROM \"HeroV2s\" \nWHERE \"owner\" = '$address' "
    }
   ]
  },
  {
   "title": "Heroes",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  name, count(1) as heroes  from \"HeroV2s\" where not is_burned and name <> '' and owner = '$address' group by name\norder by name"
    }
   ]
  },
  {
   "title": "Class",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select class, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' and owner='$address' group by class\n  order by heroes"
    }
   ]
  },
  {
   "title": "race",
   "type": "piechart",
   "description": "onchain data",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select race, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' and owner = '$address' group by race\n  order by heroes"
    }
   ]
  },
  {
   "title": "Tier",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " select tier, count(1) as heroes from \"HeroV2s\" where not is_burned and name <> '' and owner='$address' group by tier\n  order by heroes"
    }
   ]
  },
  { "title": "Issued heroes data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }, "repeat": "address" },
  {
   "title": "Hero issued type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\n  select b.type , count(1) as heroes from\n(select token_id from \"TransferHeros\" where from_address = '0x0000000000000000000000000000000000000000' and to_address = '$address'\n)a, \"HeroV2s\" b where a.token_id = b.token_id  group by b.type\n"
    }
   ]
  },
  {
   "title": "Summon Heroes type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select b.type_issued , count(1) as heroes from\n(select token_id from \"TransferHeros\" where from_address = '0x0000000000000000000000000000000000000000' and to_address = '$address'\n)a, \"HeroV2s\" b where a.token_id = b.token_id and b.\"type\" = 'SUMMON' group by b.type_issued\n\n"
    }
   ]
  }
 ]
}